name: manual-cd-push

on:
  workflow_dispatch:
    inputs:
      branch_id:
        description: "Branch, e.g: 1.13"
        default: '1.13'
        required: true
      platforms:
        description: "target platforms"
        default: 'linux/arm64,linux/amd64'
        required: true
jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch_id }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: ${{ github.event.inputs.platforms }}
          tags: lionelee/dev-environments-go:${{ github.event.inputs.branch_id }}
  